config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sms.urls')),
]

sms/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',Login,name="login"),
    path('home/',Home,name="home"),
    path('create/',create_sms,name="create_sms"),

    path('signup/',segin,name="segin"),
    path('logout/',logout,name="logout"),

    path('profile/', profile, name='profile'),

    path("upload/", upload_excel, name="upload_excel"),
    path('debitors/', debitor_list, name="debitor_list"),
    path("generate-sms/", generate_sms_view, name="generate_sms"),
    path("generate/list/",sms_list_view,name="generate-list"),
    path('debitors/', debitor_list_view, name="debitor_list"),
    path('send_sms_from_debitors/', send_sms_from_debitors, name='send_sms_from_debitors'),
    path("get_sms_progress/", get_sms_progress, name="get_sms_progress"),  # ✅ Yangi URL
    path("clear-modem-sms/", clear_modem_sms, name="clear_modem_sms"),

    path('modem-port/', modem_port_view, name="modem_port"),
    # path('send-sms/', send_sms, name="send_sms"),
    # path('sms-list/', sms_list, name="sms_list"),
]

sms/models.py
from django.db import models

class Debitor(models.Model):
    fio = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    qarz = models.DecimalField(max_digits=10, decimal_places=2)
    passport = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fio

class CreateSMS(models.Model):
    debitor = models.ForeignKey(Debitor, on_delete=models.CASCADE)  # Debitor bilan bog‘lanish
    selected = models.BooleanField(default=False)
    ijro_raqami = models.CharField(max_length=14)  # String sifatida saqlash yaxshi
    mazmuni = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return f"SMS to {self.debitor.phone} - {'Sent' if self.status else 'Pending'}"

    def __str__(self):
        return f"{self.debitor.fio} - {self.mazmuni[:20]}"


class DebitorSms(models.Model):
    ijro_ish_raqami = models.CharField(max_length=50)
    ijro_hujjat_raqami = models.CharField(max_length=50)
    ijro_hujjat_mazmuni = models.TextField()
    ijro_hujjat_summasi = models.DecimalField(max_digits=15, decimal_places=2)
    qarzdor_fish = models.CharField(max_length=255)
    telefon_raqami = models.CharField(max_length=20, blank=True, null=True)
    operator_fish = models.CharField(max_length=255, blank=True, null=True)
    operator_telefon_raqami = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return f"{self.qarzdor_fish}"


class DebitorSend(models.Model):
    ijro_ish_raqami = models.CharField(max_length=255, unique=True, verbose_name="Ijro Ish Raqami")
    ijro_hujjat_raqami = models.CharField(max_length=255, verbose_name="Ijro Hujjat Raqami")
    ijro_hujjat_mazmuni = models.CharField(max_length=500, verbose_name="Ijro Hujjat Mazmuni")
    ijro_hujjat_summasi = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="Ijro Hujjati Summasi")
    qarzdor_fish = models.CharField(max_length=255, verbose_name="Qarzdor F.I.SH")
    telefon_raqami = models.CharField(max_length=20, verbose_name="Telefon Raqami")
    operator_fish = models.CharField(max_length=255, verbose_name="Operator F.I.SH")
    operator_telefon_raqami = models.CharField(max_length=20, verbose_name="Operator Telefon Raqami")

    sms_text = models.TextField(blank=True, null=True, verbose_name="Yaratilgan SMS Matni")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan Vaqt")

    def __str__(self):
        return f"{self.qarzdor_fish} - {self.ijro_ish_raqami}"



class DebitorUsi(models.Model):
    qarzdor_fish = models.CharField(max_length=255)
    ijro_hujjat_raqami = models.CharField(max_length=255)
    ijro_hujjat_mazmuni = models.TextField()
    ijro_hujjati_summasi = models.DecimalField(max_digits=12, decimal_places=2)
    ijro_ish_raqami = models.CharField(max_length=255)
    operator_fish = models.CharField(max_length=255)
    operator_telefon_raqami = models.CharField(max_length=20)

class DebitorSendUsi(models.Model):
    debitor = models.ForeignKey(Debitor, on_delete=models.CASCADE)
    sms_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class DebitorSendGet(models.Model):
    debitor_sms = models.ForeignKey(DebitorSms, on_delete=models.CASCADE)
    sms_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class DebitorSendGetSMS(models.Model):
    debitor_sms = models.ForeignKey(DebitorSms, on_delete=models.CASCADE)
    telefon_raqami = models.CharField(max_length=20)  # Telefon raqam qo‘shildi
    sms_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.telefon_raqami} -> {self.sms_text[:30]}..."

sms/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

class DebitorForm(forms.ModelForm):
    class Meta:
        model = Debitor
        fields = ('fio', 'phone', 'qarz', 'passport')
        widgets = {
            'fio': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'qarz': forms.NumberInput(attrs={'class': 'form-control'}),
            'passport': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ProfileForm(UserChangeForm):
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        required=False,
        help_text="Оставьте поле пустым, если вы не хотите менять пароль."
    )

    class Meta:
        model = User
        fields = ['username','first_name', 'email', 'password']  # Include other fields as needed
        widgets = {
            'username': forms.TextInput(attrs={"class": "form-control"}),
            'first_name': forms.TextInput(attrs={"class" : "form-control"}),
            'email': forms.TextInput(attrs={"class": "form-control"}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        if self.cleaned_data['password']:
            user.set_password(self.cleaned_data['password'])  # Update the password only if a new one is entered
        if commit:
            user.save()
        return user

class ExcelUploadForm(forms.Form):
    file = forms.FileField()


class CreateSMSForm(forms.ModelForm):
    class Meta:
        model = CreateSMS
        fields = ('debitor', 'ijro_raqami', 'mazmuni', 'selected')
        widgets = {
            'debitor': forms.Select(attrs={'class': 'form-control'}),  # Dropdown
            'ijro_raqami': forms.TextInput(attrs={'class': 'form-control'}),
            'mazmuni': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'selected': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

sms/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import HttpResponse
from .forms import *
import pandas as pd
import serial.tools.list_ports
import serial
from gsmmodem.modem import GsmModem
import re
import time
import textwrap
import binascii
from .models import *
import json
from django.http import JsonResponse
from django.shortcuts import render
# Create your views here.

@login_required(login_url="login")
def Home(request):
    return render(request,"base.html")

@login_required(login_url="login")
def create_sms(request):
    form = DebitorForm()
    form2 = CreateSMSForm()

    if request.method == "POST":
        form = DebitorForm(request.POST)
        form2 = CreateSMSForm(request.POST)

        if form.is_valid():
            form.save()
        if form2.is_valid():
            form2.save()
            return redirect('create_sms')

    context = {
        "form": form,
        "form2": form2,
    }

    return render(request, "create_sms.html", context)





@login_required(login_url="login")
def segin(request):
    error_massage = None
    if request.POST:
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        if password != password2:
            error_massage = "Terilgen parol birdey boliw kerek!"
        else:
            my_user = User.objects.create_user(username=username,first_name=first_name, email=email, password=password)
            my_user.first_name = first_name
            return redirect("login")
    return render(request,"signup.html", {"error_massage": error_massage})

def Login(request):
    error_message = None
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user is not None:
                login(request, user)
                return redirect("home")
        else:
            error_message = "Login yamasa paroldi qate kiritiniz, basqatdan urinip korin!!!"

    return render(request, "login.html", {"error_message": error_message})

@login_required(login_url="login")
def logout(request):
    auth_logout(request)
    return redirect("login")

@login_required(login_url="login")
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProfileForm(instance=request.user)

    return render(request, 'profile.html', {'form': form, 'username': request.user.username})


@login_required(login_url="login")
def upload_excel(request):
    if request.method == "POST" and request.FILES.get("file"):
        file = request.FILES["file"]
        df = pd.read_excel(file, dtype=str)

        df.columns = df.columns.str.strip()

        required_columns = [
            "Ijro ish raqami",
            "Ijro hujjat raqami",
            "Ijro hujjat mazmuni",
            "Qoldiq summa",
            "Qarzdor F.I.SH",
            "Telefon raqami mavjudmi?",
            "Operator F.I.SH",
            "operator Telefon raqami mavjudmi?"
        ]
        for col in required_columns:
            if col not in df.columns:
                messages.error(request, f"Xatolik: '{col}' ustuni Excel faylida topilmadi!")
                return redirect("upload_excel")
                # return HttpResponse(f"Xatolik: '{col}' Excel faylidan tabilmadi!", status=400)

        def clean_number(value):
            if isinstance(value, str):
                value = value.replace(" ", "").replace(",", ".")
            try:
                return round(float(value), 2)
            except ValueError:
                return None

        df["Qoldiq summa"] = df["Qoldiq summa"].apply(clean_number)

        # Bazaga saqlash
        for _, row in df.iterrows():
            DebitorSms.objects.create(
                ijro_ish_raqami=row["Ijro ish raqami"],
                ijro_hujjat_raqami=row["Ijro hujjat raqami"],
                ijro_hujjat_mazmuni=row["Ijro hujjat mazmuni"],
                ijro_hujjat_summasi=row["Qoldiq summa"],
                qarzdor_fish=row["Qarzdor F.I.SH"],
                telefon_raqami=row["Telefon raqami mavjudmi?"],
                operator_fish=row["Operator F.I.SH"],
                operator_telefon_raqami=row["operator Telefon raqami mavjudmi?"]
            )

        messages.success(request, "✅ Excel mag'luwmatlar toliq juklendi!")
        return redirect("upload_excel")
        # return HttpResponse("Excel Mag'luwmatlar toliq juklendi!")

    return render(request, "upload_excel.html")

def debitor_list(request):
    debitors = DebitorSms.objects.all()
    return render(request, "debitor_list.html", {"debitors": debitors})

def format_phone_number(phone_number):
    """Telefon raqamni +998XXXXXXXXX formatiga o‘tkazish"""
    phone_number = re.sub(r'\D', '', phone_number)  # ❌ Raqam bo‘lmagan belgilarni olib tashlash

    if phone_number.startswith("998"):
        phone_number = f"+{phone_number}"  # ✅ Agar oldida 998 bo‘lsa, faqat + qo‘shiladi
    elif len(phone_number) == 9:
        phone_number = f"+998{phone_number}"  # ✅ Agar faqat 9 xonali raqam bo‘lsa, +998 qo‘shiladi

    return phone_number

def generate_sms_view(request):
    if request.method == "POST":
        debitors = DebitorSms.objects.all()

        for debitor in debitors:
            # 🔹 Telefon raqamni formatlash
            formatted_phone = format_phone_number(debitor.telefon_raqami)

            # 🔹 Agar ushbu debitor uchun oldin SMS generatsiya qilingan bo'lsa, o'tkazib yuboramiz
            if DebitorSendGetSMS.objects.filter(debitor_sms=debitor).exists():
                continue

            # 🔹 SMS matni generatsiyasi
            sms_text = f"Prokuratura Byurosi tomonidan {debitor.qarzdor_fish} Sizga nisbatan {debitor.ijro_hujjat_summasi} so'mlik {debitor.ijro_hujjat_raqami} sonli ijro ishi mavjud. Jami {debitor.ijro_hujjat_summasi} so'm to'lanmagan taqdirda, mol-mulkingizga taqiq solinib, avtotransportingizga qidiruv e’lon qilinadi. Agarda qarzdorlik o’z vaqtida qoplanmagan taqdirda BXM ning 5 baravarigacha jarima qollanilishi haqida ogohlantiramiz. To'lov uchun ID: {debitor.ijro_ish_raqami} Davlat ijrochisi: {debitor.operator_fish} Tel: {debitor.operator_telefon_raqami}, +998939202082"

            # 🔹 Yangi SMS generatsiya qilib bazaga saqlaymiz
            DebitorSendGetSMS.objects.create(debitor_sms=debitor, telefon_raqami=formatted_phone, sms_text=sms_text)

        return redirect("generate-list")

    return render(request, "generate_sms.html")


# def generate_sms_view(request):
#     if request.method == "POST":
#         debitors = DebitorSms.objects.all()
#         for debitor in debitors:
#             # sms_text = f"Ҳурматли {debitor.qarzdor_fish}, Сизнинг {debitor.ijro_ish_raqami} суд иши бўйича {debitor.ijro_hujjat_raqami}. Сизда {debitor.ijro_hujjat_mazmuni} {debitor.ijro_hujjat_summasi} сўм қарздорлик мавжуд. Тўлов учун ИД: {debitor.ijro_ish_raqami}. Ижрочи {debitor.operator_fish}, Тел: {debitor.operator_telefon_raqami} mib.uz"
#             sms_text = f"Prokuratura Byurosi tomonidan {debitor.qarzdor_fish} Sizga nisbatan {debitor.ijro_hujjat_summasi} so'mlik {debitor.ijro_hujjat_raqami} sonli ijro ishi mavjud. Jami {debitor.ijro_hujjat_summasi} so'm to'lanmagan taqdirda, mol-mulkingizga taqiq solinib, avtotransportingizga qidiruv e’lon qilinadi. Agarda qarzdorlik o’z vaqtida qoplanmagan taqdirda BXM ning 5 baravarigacha jarima qollanilishi haqida ogohlantiramiz. To'lov uchun ID: {debitor.ijro_ish_raqami} Davlat ijrochisi: {debitor.operator_fish} Tel: {debitor.operator_telefon_raqami}"
#             # sms_text = f"{debitor.qarzdor_fish} {debitor.ijro_hujjat_summasi} {debitor.ijro_hujjat_raqami} {debitor.ijro_hujjat_summasi} {debitor.ijro_ish_raqami}, {debitor.operator_fish} {debitor.operator_telefon_raqami}"
#
#             # DebitorSend bazag'a saqlaw
#             DebitorSendGet.objects.create(debitor_sms=debitor, sms_text=sms_text)
#
#         return redirect("generate-list")
#
#     return render(request, "generate_sms.html")

def sms_list_view(request):
    sms_list = DebitorSendGetSMS.objects.all().order_by("-created_at")
    return render(request, "sms_list.html", {"sms_list": sms_list})



def debitor_list_view(request):
    debitors = DebitorSend.objects.all().order_by('-id')  # So'nggi qo‘shilganlar birinchi chiqadi
    return render(request, 'generate_list.html', {'debitors': debitors})

# Start USB modem
def get_modem_port():
    ports = serial.tools.list_ports.comports()
    for port in ports:
        if "ZTE Proprietary" in port.description:  # Huawei modemni topish
            return port.device
    return "COM18"

# def format_phone_number(phone_number):
#     # ✅ 1️⃣ Bo‘sh joylar, chiziqlar va nuqtalarni olib tashlash
#     phone_number = re.sub(r"[^\d]", "", phone_number)
#
#     # ✅ 2️⃣ Agar uzunligi 9 bo‘lsa (masalan, "937156633"), +998 qo‘shish
#     if len(phone_number) == 9 and phone_number.startswith("9"):
#         phone_number = f"+998{phone_number}"
#
#     # ✅ 3️⃣ Agar allaqachon +998 bilan boshlangan bo‘lsa, o‘zgartirmaslik
#     elif len(phone_number) == 12 and phone_number.startswith("998"):
#         phone_number = f"+{phone_number}"
#
#     return phone_number


def modem_port_view(request):
    port = get_modem_port()
    return render(request, "modem_port.html", {"port": port})

templates/create_sms.html
{% extends 'base.html' %}
{% load static %}
{% block create_sms %}
    <section class="container">
            <div class="row justify-content-around text-center text-white mt-5">
                <div class="col-sm-8">
                    <h3>SMS Mag'lumatlardi jaratiw bo'limi</h3>
                </div>
            </div>
            <div class="row justify-content-around mt-3">
                <div class="col-sm-12">
<!--                    <a href="#" class="btn btn-primary float-end">Add</a>-->


                </div>
            </div>

            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        <form action="{% url 'create_sms' %}" method="post">
                            {% csrf_token %}  <!-- CSRF tokeni himoya uchun kerak -->
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Saqlash</button>
                        </form>
                    </div>
                    <div class="col-sm-12 col-xl-6">
                        <form action="{% url 'create_sms' %}" method="post">
                            {% csrf_token %}  <!-- CSRF tokeni himoya uchun kerak -->
                            {{ form2.as_p }}
                            <button type="submit" class="btn btn-primary">Saqlash</button>
                        </form>
                    </div>
                </div>
            </div>



        </section>
{% endblock create_sms %}

templates/debitor_list.html
{% extends 'base.html' %}
{% load static %}
{% block send_list %}
<div class="row justify-content-around mt-4 text-center">
                <div class="bg-light rounded h-100 p-4">
                    <h2>📩 Excelldegi kelip tusken kestesi</h2>
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Ijro Ish Raqami</th>
                                    <th scope="col">Ijro Hujjat Raqami</th>
                                    <th scope="col">Ijro Hujjat Mazmuni</th>
                                    <th scope="col">Ijro Hujjati Summasi</th>
                                    <th scope="col">Qarzdor F.I.SH</th>
                                    <th scope="col">Telefon Raqami</th>
                                    <th scope="col">Operator F.I.SH</th>
                                    <th scope="col">Operator Telefon Raqami</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for debitor in debitors %}
                                <tr>
                                    <td scope="row">{{ forloop.counter }}</td>
                                    <td>{{ debitor.ijro_ish_raqami }}</td>
                                    <td>{{ debitor.ijro_hujjat_raqami }}</td>
                                    <td>{{ debitor.ijro_hujjat_mazmuni }}</td>
                                    <td>{{ debitor.ijro_hujjat_summasi }}</td>
                                    <td>{{ debitor.qarzdor_fish }}</td>
                                    <td>{{ debitor.telefon_raqami }}</td>
                                    <td>{{ debitor.operator_fish }}</td>
                                    <td>{{ debitor.operator_telefon_raqami }}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="9" class="text-center">Hazirshe malumat joq</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
</div>
{% endblock send_list %}

templates/generate_sms.html
{% extends 'base.html' %}
{% load static %}
{% block generate_sms %}
<div class="row justify-content-around mt-4 text-center">
                <div class="col-sm-12">
                    <h2>📩 Generatsiya SMS</h2>

                    <form method="post" action="{% url 'generate_sms' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Generatsiya</button>
                    </form>
                </div>
</div>
{% endblock generate_sms %}

templates/list.html
<!--Bul bet shornavek esabinda qolanilip atir-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row justify-content-around mt-4 text-center">
                <div class="col-sm-12">
                    <table class="table table-hover">
                       <thead>
                            <tr>
                              <th scope="col">ID</th>
                              <th scope="col">SELECTED</th>
                              <th scope="col">IJRO RAQAMI</th>
                              <th scope="col">MAZMUNI</th>
                                <th scope="col">QARZI</th>
                                <th scope="col">F.I.O USER</th>
                                <th scope="col">PASPORT USER</th>
                                <th scope="col">TELEFON RAQAMI USER</th>
                                <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>

                            <tr>
                              <th scope="row">1</th>
                              <td>S</td>
                              <td>230122011456</td>
                              <td>Sizde qarz bar</td>
                                <td>350 so'm</td>
                                <td>JOLDASBAEV FARXAT DANIYAROVICH</td>
                                <td>AD 123456</td>
                                <td>+998934562514</td>
                                <td>
                                    <table>
                                        <tr>
                                            <td>
                                                <form action="#" method="POST">

                                                    <input type="hidden" class="btn btn-danger btn-sm" name="id" value="">
                                                    <input type="submit" class="btn btn-danger btn-sm" value="Удалить">
                                                </form>
                                            </td>
                                            <td>
                                                <a href="#" class="btn btn-info btn-sm">Изменять</a>
                                            </td>
                                        </tr>
                                    </table>

                                </td>
                            </tr>


                            </tbody>
                    </table>
                </div>
            </div>
</body>
</html>

# SMS Dizimi
<h3>📋 Jo‘natish uchun mavjud SMS lar</h3>
                <table border="1">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Qarzdor</th>
                            <th>Telefon raqami</th>
                            <th>SMS matni</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for sms in sms_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ sms.qarzdor_fish }}</td>
                            <td>{{ sms.telefon_raqami }}</td>
                            <td>
                                {% with sms_text=sms.debitorsendget_set.first %}
                                    {{ sms_text.sms_text|default:"Mavjud emas" }}
                                {% endwith %}
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">📭 Jo‘natish uchun hech qanday SMS mavjud emas</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

# SMS END


<!-- SMS natijalari -->
{% if sent_sms %}
<h4>✅ Yuborilgan SMSlar:</h4>
<ul>
    {% for sms in sent_sms %}
        <li>📩 {{ sms.phone_number }}: {{ sms.sms_text }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if failed_sms %}
<h4>❌ Xato bo‘lgan SMSlar:</h4>
<ul>
    {% for sms in failed_sms %}
        <li>⚠️ {{ sms.phone_number }}: {{ sms.sms_text }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if invalid_sms %}
<h4>⚠️ Noto‘g‘ri formatdagi SMSlar:</h4>
<ul>
    {% for sms in invalid_sms %}
        <li>❌ {{ sms.phone_number }}: {{ sms.sms_text }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if error %}
<p style="color: red;">{{ error }}</p>
{% endif %}


                <!-- SMS Jo‘natish tugmasi -->
<!--                <form id="sms-form">-->
<!--                    {% csrf_token %}-->
<!--                    <button type="button" id="send-sms-btn" class="btn btn-primary" onclick="sendSMS()">📤 SMS Jiberiw</button>-->
<!--                </form>-->
<!--            <h3>📋 Jeberiw ge tayin turg'an smsler</h3>-->
<!--                <table border="1">-->
<!--                    <thead>-->
<!--                        <tr>-->
<!--                            <th>#</th>-->
<!--                            <th>Telefon nomer</th>-->
<!--                            <th>SMS text</th>-->
<!--                        </tr>-->
<!--                    </thead>-->
<!--                    <tbody>-->
<!--                        {% for sms in sms_list %}-->
<!--                        <tr>-->
<!--                            <td>{{ forloop.counter }}</td>-->
<!--                            <td>{{ sms.telefon_raqami }}</td>-->
<!--                            <td>{{ sms.sms_text }}</td>-->
<!--                        </tr>-->
<!--                        {% empty %}-->
<!--                        <tr>-->
<!--                            <td colspan="4">📭 Jeberiw ushin hesh qanday smsler ko'rinbedi</td>-->
<!--                        </tr>-->
<!--                        {% endfor %}-->
<!--                    </tbody>-->
<!--                </table>-->



<!--    &lt;!&ndash; Jo‘natilmagan SMSlar jadvali &ndash;&gt;-->
<!--        {% if failed_sms_list %}-->
<!--        <h3 style="color: red;">❌ Yuborilmagan SMSlar:</h3>-->
<!--        <table border="1">-->
<!--            <thead>-->
<!--                <tr>-->
<!--                    <th>Telefon raqam</th>-->
<!--                    <th>SMS matni</th>-->
<!--                    <th>Holat</th>-->
<!--                </tr>-->
<!--            </thead>-->
<!--            <tbody>-->
<!--                {% for sms in failed_sms_list %}-->
<!--                <tr style="color: red;">-->
<!--                    <td>{{ sms.phone_number }}</td>-->
<!--                    <td>{{ sms.sms_text }}</td>-->
<!--                    <td>{{ sms.status }}</td>-->
<!--                </tr>-->
<!--                {% endfor %}-->
<!--            </tbody>-->
<!--        </table>-->
<!--        {% endif %}-->

<!--    &lt;!&ndash; Yuborilgan SMSlar ro‘yxati &ndash;&gt;-->
<!--    {% if sent_sms_list %}-->
<!--    <h3 style="color: green;">✅ Yuborilgan SMSlar:</h3>-->
<!--    <table border="1">-->
<!--        <thead>-->
<!--            <tr>-->
<!--                <th>Telefon raqam</th>-->
<!--                <th>SMS matni</th>-->
<!--                <th>Holat</th>-->
<!--            </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--            {% for sms in sent_sms_list %}-->
<!--            <tr style="color: green;">-->
<!--                <td>{{ sms.phone_number }}</td>-->
<!--                <td>{{ sms.sms_text }}</td>-->
<!--                <td>{{ sms.status }}</td>-->
<!--            </tr>-->
<!--            {% endfor %}-->
<!--        </tbody>-->
<!--    </table>-->
<!--    {% endif %}-->